### ISSUE TITLE
Allow for a fully manual process of picking circles

### ISSUE THREAD

**Issue by TessFerrandez** [digitaldias/DropSampler#17]
As a backup - we should allow for a fully manual process where the user picks all the circles (with no auto detection of circles) - probably also allowing different size circles

**Comment by TessFerrandez** [comment]
This task is specifically to figure out how this would look and what would be needed to implement this so I will discuss this with Pedram on Monday

**Comment by peterbryntesson** [comment]
I think we already have this on feature/add-missing-circles

**Comment by TessFerrandez** [comment]
Yes, we can close this one
