### ISSUE TITLE
Settle on a common, agreed upon export CSV format

### ISSUE THREAD

**Issue by digitaldias** [digitaldias/DropSampler#5]

**Comment by TessFerrandez** [comment]
I will discuss this with Pedram om the 14th

**Comment by TessFerrandez** [comment]
Before | A1 |   |   | A2 |   |   | B1 |   |   | B2 |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
  | R | G | B | R | G | B | R | G | B | R | G | B
1-A | 99 | 183 | 221 | 102 | 185 | 223 | 105 | 185 | 222 | 105 | 185 | 222
1-B | 93 | 181 | 222 | 103 | 185 | 222 | 106 | 186 | 221 | 106 | 186 | 221
2-A | 134 | 196 | 228 | 124 | 192 | 225 | 129 | 193 | 225 | 129 | 193 | 225

Sample Excel format - each row is one row of dots
